export type MenuItem = {
    name: string;
    price: number | string;
    desc: string;
    veg: boolean;
};

export const menuData: Record<string, MenuItem[]> = {
    "Thali": [
        { name: "Veg Special Thali", price: 180, desc: "Dal, 2 Sabzi, Roti, Rice, Salad, Pickle, Papad, Sweet", veg: true },
        { name: "Chicken Thali", price: 200, desc: "Chicken Sukka, Chicken Curry, Roti/Bhakri, Rice, Salad", veg: false },
        { name: "Mutton Thali", price: 280, desc: "Mutton Sukka, Mutton Curry, Roti/Bhakri, Rice, Salad", veg: false },
        { name: "Prawns Thali", price: "APS", desc: "Prawns Fry, Prawns Curry, Roti/Bhakri, Rice, Salad", veg: false },
        { name: "Surmai Thali", price: "APS", desc: "Surmai Fry, Fish Curry, Roti/Bhakri, Rice, Salad", veg: false },
    ],
    "Tandoor Non-Veg": [
        { name: "Chicken Tandoori (Full/Half)", price: "370/240", desc: "Classic clay oven roasted chicken", veg: false },
        { name: "Chicken Reshmi Tr (Full/Half)", price: "390/270", desc: "Creamy marinated roasted chicken", veg: false },
        { name: "Chicken Banjara Tr (Full/Half)", price: "390/270", desc: "Spiced green herb marinated chicken", veg: false },
        { name: "Chicken Afgani Tr (Full/Half)", price: "390/270", desc: "Mild creamy white marinade roasted chicken", veg: false },
        { name: "Chicken White Tr (Full/Half)", price: "390/270", desc: "Succulent white cream roasted chicken", veg: false },
        { name: "Chicken Pahadi Tr (Full/Half)", price: "390/270", desc: "Green mint and coriander marinated chicken", veg: false },
        { name: "Prawns Tandoori", price: "APS", desc: "Jumbo prawns grilled in tandoor", veg: false },
        { name: "Pomfret Tandoori", price: "APS", desc: "Whole pomfret marinated and grilled", veg: false },
        { name: "Tandoori Chicken Lollipop", price: 240, desc: "Spicy chicken wings roasted in clay oven", veg: false },
        { name: "Chicken Tangdi kabab 2Pc", price: 340, desc: "Succulent chicken drumsticks grilled", veg: false },
        { name: "Chicken Tangdi kabab 1Pc", price: 190, desc: "Single chicken drumstick grilled", veg: false },
        { name: "Chicken Malai Tikka", price: 260, desc: "Boneless chicken in cream and cheese", veg: false },
        { name: "Chicken Kalimiri Tikka", price: 260, desc: "Chicken nuggets flavored with black pepper", veg: false },
        { name: "Chicken Achari Tikka", price: 260, desc: "Pickle flavored boneless chicken", veg: false },
        { name: "Chicken Reshmi Tikka", price: 260, desc: "Melt-in-mouth creamy chicken tikka", veg: false },
        { name: "Chicken Pahadi kabab", price: 260, desc: "Boneless chicken with green herb marinade", veg: false },
        { name: "Chicken Lasooni Tikka", price: 270, desc: "Garlic flavored boneless roasted chicken", veg: false },
        { name: "Chicken Seekh kabab", price: 270, desc: "Minced chicken skewers grilled", veg: false },
        { name: "Chicken Rogan kabab", price: 340, desc: "Richly spiced traditional chicken kabab", veg: false },
        { name: "Chicken Dum kabab", price: 300, desc: "Slow cooked juicy chicken kababs", veg: false },
        { name: "Murg Tang Talwar", price: 300, desc: "Sword-skewered spicy chicken drumsticks", veg: false },
        { name: "Chicken Tikka", price: 260, desc: "Spicy red marinated boneless chicken", veg: false },
        { name: "Chicken Banjara kabab", price: 270, desc: "Spicy herb marinated chicken kabab", veg: false },
        { name: "Chicken Adraki kabab", price: 270, desc: "Ginger flavored roasted chicken kabab", veg: false },
        { name: "Chicken Platter", price: "APS", desc: "Assorted non-veg tandoory items", veg: false },
        { name: "Baby / Surmai Tandoori", price: "APS", desc: "Fresh fish grilled in tandoor", veg: false },
    ],
    "Tandoor Veg": [
        { name: "Veg Seekh Kabab", price: 250, desc: "Minced vegetable skewers grilled", veg: true },
        { name: "Aloo Tandoori", price: 180, desc: "Baby potatoes marinated and grilled", veg: true },
        { name: "Paneer Tikka", price: 250, desc: "Cottage cheese cubes grilled with spices", veg: true },
        { name: "Paneer Malai Tikka", price: 260, desc: "Creamy mild marinated paneer", veg: true },
        { name: "Paneer Kalimiri Tikka", price: 260, desc: "Black pepper flavored paneer tikka", veg: true },
        { name: "Paneer Lasooni Tikka", price: 260, desc: "Garlic infused grilled paneer", veg: true },
        { name: "Paneer Hariyali Tikka", price: 260, desc: "Green herb marinated grilled paneer", veg: true },
        { name: "Paneer Dam Kabab", price: 270, desc: "Slow roasted tender paneer kabab", veg: true },
        { name: "Mushroom Tandoori", price: 260, desc: "Fresh mushrooms marinated and grilled", veg: true },
        { name: "Stoff Mushroom", price: 280, desc: "Cheese and herb stuffed grilled mushrooms", veg: true },
        { name: "Baby Corn Mushroom Tr", price: 260, desc: "Corn and mushroom assorted tandoor", veg: true },
    ],
    "Indian Veg": [
        { name: "Dal Fry", price: 150, desc: "Yellow lentils tempered with Indian spices", veg: true },
        { name: "Dal Tadka", price: 160, desc: "Lentils with double tempering of garlic & cumin", veg: true },
        { name: "Dal Kolhapuri", price: 160, desc: "Spicy Maharashtrian style dal", veg: true },
        { name: "Paneer Handi", price: 180, desc: "Paneer cooked in traditional clay pot", veg: true },
        { name: "Paneer Kadai", price: 180, desc: "Paneer with capsicum in spicy gravy", veg: true },
        { name: "Paneer Kaju", price: 200, desc: "Cottage cheese with cashew rich gravy", veg: true },
        { name: "Palak Paneer", price: 180, desc: "Paneer in smooth spinach gravy", veg: true },
        { name: "Paneer Butter Masala", price: 200, desc: "Paneer in rich buttery tomato gravy", veg: true },
        { name: "Paneer Tikka Masala", price: 240, desc: "Grilled paneer in spicy onion-tomato gravy", veg: true },
        { name: "Kaju Masala", price: 210, desc: "Roasted Cashews in spicy brown gravy", veg: true },
        { name: "Paneer Kolhapuri", price: 180, desc: "Spicy and flavorful tandoori paneer gravy", veg: true },
        { name: "Aloo Palak", price: 160, desc: "Potatoes in creamy spinach gravy", veg: true },
        { name: "Veg Kolhapuri", price: 175, desc: "Mixed veg in spicy Maharashtrian gravy", veg: true },
        { name: "Mushroom Masala", price: 175, desc: "Mushroom in spicy tomato onion gravy", veg: true },
        { name: "Malai Kofta", price: 220, desc: "Paneer dumplings in sweet creamy gravy", veg: true },
    ],
    "Indian Non-Veg": [
        { name: "Chicken Masala", price: 190, desc: "Traditional chicken curry with spices", veg: false },
        { name: "Chicken Sukka", price: 210, desc: "Dry fried chicken with coastal spices", veg: false },
        { name: "Chicken Mughlai", price: 215, desc: "Rich chicken in egg based creamy gravy", veg: false },
        { name: "Butter Chicken (Full/Half)", price: "360/550", desc: "Tandoori chicken in butter tomato gravy", veg: false },
        { name: "Chicken Tikka Masala", price: 280, desc: "Grilled chicken pieces in rich curry", veg: false },
        { name: "Chicken Handi (Full/Half)", price: "550/350", desc: "Slow cooked chicken in clay pot", veg: false },
        { name: "Chicken Lapeta", price: 390, desc: "Thick spicy gravy coated chicken", veg: false },
        { name: "Mutton Masala", price: 260, desc: "Classic mutton curry with thick gravy", veg: false },
        { name: "Mutton Sukka", price: 290, desc: "Spicy dry roasted mutton with coconut", veg: false },
        { name: "Mutton Roganjosh", price: 290, desc: "Kashmiri style mutton with red chili", veg: false },
        { name: "Mutton Kolhapuri", price: 295, desc: "Fiery spicy mutton preparation", veg: false },
        { name: "Agri Chicken Masala", price: 210, desc: "Traditional Agri style chicken", veg: false },
        { name: "Egg Masala", price: 140, desc: "Boiled eggs in onion tomato gravy", veg: false },
        { name: "Chicken Saagwalla", price: 285, desc: "Chicken cooked in spinach gravy", veg: false },
    ],
    "Chinese Veg": [
        { name: "Veg Crispy", price: 190, desc: "Fried vegetables in sweet & spicy sauce", veg: true },
        { name: "Veg Manchurian", price: 180, desc: "Veg balls in dark soy ginger sauce", veg: true },
        { name: "Paneer Crispy", price: 220, desc: "Golden fried paneer in hot garlic sauce", veg: true },
        { name: "Paneer Chilly", price: 210, desc: "Cottage cheese tossed with peppers", veg: true },
        { name: "Veg Spring Roll", price: 210, desc: "Crispy rolls stuffed with veggies", veg: true },
        { name: "Veg Hakka Noodle", price: 180, desc: "Classic stir fried vegetables noodles", veg: true },
        { name: "Veg Schezwan Fried Rice", price: 190, desc: "Rice tossed in spicy Schezwan sauce", veg: true },
        { name: "Mushroom Fried Rice", price: 190, desc: "Rice tossed with fresh mushrooms", veg: true },
        { name: "Veg Manchow Soup", price: 110, desc: "Spicy soy soup with crunchy noodles", veg: true },
        { name: "Sweet Corn Soup", price: 110, desc: "Mild creamy golden corn soup", veg: true },
    ],
    "Chinese Non-Veg": [
        { name: "Chicken Crispy", price: 220, desc: "Fried shredded chicken with chili honey", veg: false },
        { name: "Chicken Lollipop", price: 200, desc: "Deep fried chicken wings Indian Chinese style", veg: false },
        { name: "Chicken 65", price: 210, desc: "Spicy curry leaf tempered fried chicken", veg: false },
        { name: "Chicken Chilly", price: 210, desc: "Wok tossed chicken with soy and peppers", veg: false },
        { name: "Chicken Fried Rice", price: 190, desc: "Rice tossed with chicken and egg", veg: false },
        { name: "Chicken Hakka Noodle", price: 190, desc: "Stir fried chicken and egg noodles", veg: false },
        { name: "Chicken Manchow Soup", price: 120, desc: "Spicy chicken soup with coriander", veg: false },
        { name: "Drums Of Heaven", price: 220, desc: "Chicken lollipop tossed in spicy sauce", veg: false },
        { name: "Chicken Schezwan Rice", price: 210, desc: "Spicy Schezwan flavored chicken rice", veg: false },
    ],
    "Rice & Biryani": [
        { name: "Veg Biryani", price: 170, desc: "Fragrant rice cooked with mixed vegetables", veg: true },
        { name: "Paneer Tikka Biryani", price: 250, desc: "Biryani with grilled paneer tikka", veg: true },
        { name: "Chicken Biryani (Full/Half)", price: "210/120", desc: "Dum cooked aromatic chicken rice", veg: false },
        { name: "Chicken Tikka Biryani", price: 270, desc: "Biryani with spicy chicken tikka pieces", veg: false },
        { name: "Egg Biryani", price: 160, desc: "Spiced rice with boiled eggs", veg: false },
        { name: "Dal Khichdi", price: 150, desc: "Comforting rice and lentil porridge", veg: true },
        { name: "Jeera Rice", price: "70/110", desc: "Cumin tempered steamed basmati rice", veg: true },
        { name: "Steam Rice", price: "70/100", desc: "Plain steamed high quality basmati rice", veg: true },
    ],
    "Sea Food": [
        { name: "Bangara Fry", price: "APS", desc: "Mackerel fish deep fried with spices", veg: false },
        { name: "Pomfret Tawa Fry", price: "APS", desc: "Whole pomfret shallow fried on iron tawa", veg: false },
        { name: "Surmai Rawa Fry", price: "APS", desc: "King fish coated with semolina & fried", veg: false },
        { name: "Prawns Masala", price: "APS", desc: "Spicy coastal style prawns gravy", veg: false },
        { name: "Bombil Fry", price: "APS", desc: "Crispy Bombay Duck fish fry", veg: false },
        { name: "Fish Biryani", price: "APS", desc: "Fragrant rice cooked with fish", veg: false },
    ],
    "Breads & Accompaniments": [
        { name: "Tandoori Roti", price: 20, desc: "Whole wheat bread baked in clay oven", veg: true },
        { name: "Butter Naan", price: 40, desc: "Soft refined flour bread with butter", veg: true },
        { name: "Garlic Naan", price: 65, desc: "Naan infused with fresh garlic", veg: true },
        { name: "Cheese Garlic Naan", price: 95, desc: "Cheese stuffed garlic flavored naan", veg: true },
        { name: "Masala Papad", price: 50, desc: "Roasted papad with spicy onion tomato", veg: true },
        { name: "Green Salad", price: 80, desc: "Fresh seasonal vegetable slices", veg: true },
    ]
};
